language: java

before_install:
     - sudo apt-get -qq update
     - sudo apt-get install oracle-java7-installer 

install: true

script: mvn clean compile test

jdk: 
     - oraclejdk7
     - oraclejdk8


notifications:
     email: false


os:
    - linux


branches:
    only:
        - master
